name: Testing
on:
  push:
jobs:
  Testing:
    runs-on: Ubuntu-latest
    steps:
      - name: printing OS
        run: uname
      - name: printing Directory
        run: pwd
      - name: printing files
        run: ls